sudo: false

language: node_js

node_js:
  - "10.4.0"
  - "10.9.0"
  - "10"
  - "12"

os:
  - linux
  - windows

dist: xenial

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

notifications:
  email: false
